# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.
[kube_control_plane]
 master01.devopsmaffia.local ansible_host=master01  ip=10.0.0.144 etcd_member_name=etcd1 ansible_become_pass=nahla
 master02.devopsmaffia.local ansible_host=master02  ip=10.0.0.184 etcd_member_name=etcd2 ansible_become_pass=nahla
 master03.devopsmaffia.local  ansible_host=master03  ip=10.0.0.173 etcd_member_name=etcd3 ansible_become_pass=nahla

[etcd:children]
kube_control_plane

[kube_node]
 worker01.devopsmaffia.local ansible_host=worker01  ip=10.0.0.105 ansible_become_pass=nahla
 worker02.devopsmaffia.local ansible_host=worker02  ip=10.0.0.121 ansible_become_pass=nahla
 worker03.devopsmaffia.local ansible_host=worker03  ip=10.0.0.134 ansible_become_pass=nahla
 worker04.devopsmaffia.local ansible_host=worker04  ip=10.0.0.160 ansible_become_pass=nahla
 worker05.devopsmaffia.local ansible_host=worker05  ip=10.0.0.127 ansible_become_pass=nahla

[calico_rr]


[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr